version: '3'

services:
  wheelsunauth:
    image: jnerdq/image-wheelsun_auth_ms:latest
    expose:
      - 8080
    networks:
      - mynetwork

  wheelsunuserms:
    image: jivegabe/image-wheelsun_user_ms
    expose:
      - 8000
    networks:
      - mynetwork

  wheelsunmq:
    image: rabbitmq:3.13-management
    expose:
      - 5672
      - 15672
    networks:
      - mynetwork
      
  wheelsuntransactionms:
    image: cquilaguy12/image-wheelsun_transaction_ms
    expose:
      - 3000

    networks:
      - mynetwork
      
  wheelsuntripms:
    image: ccortesra/wheels
    expose:
      - 3002
    
    networks:
      - mynetwork

  wheelsunag:
    image: jivegabe/image-wheelsun_ag-no_ldap
    expose:
      - 8100
    networks:
      - mynetwork
    depends_on:
      - wheelsunauth
      - wheelsunuserms
      - wheelsuntransactionms
      - wheelsuntripms
      - wheelsunmq

  nginx_wheelsunag:
    image: cquilaguy12/image-wheelsun_proxyag
    ports:
      - "81:81"
      - "444:444"
    networks:
      - mynetwork
    depends_on:
      - wheelsunag
    
networks:
  mynetwork:
    driver: bridge