version: '3'

services:
  wheelsunauth:
    image: jnerdq/image-wheelsun_auth_ms:latest
    expose:
      - 8080
    networks:
      mynetwork:
        aliases:
          - wheelsunauth

  wheelsunuserms:
    image: jivegabe/image-wheelsun_user_ms
    expose:
      - 8000
    networks:
      mynetwork:
        aliases:
          - wheelsunuserms

  wheelsunmq:
    image: rabbitmq:3.13-management
    expose:
      - 5672
      - 15672
    networks:
      mynetwork:
        aliases:
          - wheelsunmq

  wheelsuntransactionms:
    image: cquilaguy12/image-wheelsun_transaction_ms
    expose:
      - 3000
    networks:
      mynetwork:
        aliases:
          - wheelsuntransactionms

  wheelsuntripms:
    image: ccortesra/wheels
    expose:
      - 3002
    networks:
      mynetwork:
        aliases:
          - wheelsuntripms

  wheelsunAg:
    image: jivegabe/image-wheelsun_ag-ldap_cloud
    expose:
      - 8100
    networks:
      mynetwork:
        aliases:
          - wheelsunAg
    depends_on:
      - wheelsunauth
      - wheelsunuserms
      - wheelsuntransactionms
      - wheelsuntripms
      - wheelsunmq

  nginx_wheelsunag:
    image: cquilaguy12/image-wheelsun_proxyag
    ports:
      - "81:81"
    networks:
      mynetwork:
        aliases:
          - nginx_wheelsunag
    depends_on:
      - wheelsunAg

networks:
  mynetwork:
    driver: bridge
