version: '3'

services:
  wheels_front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9200:9200"  # Adjust the ports as needed
    volumes:
      - .:/app  # Mount the Flutter app code into the container
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "90:80"  # Adjust the ports as needed
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the Nginx configuration file
      - ./certs:/etc/nginx/certs  # Mount SSL certificate and key files
      - .:/app  # Mount the Flutter app code into the Nginx container

    depends_on:
      - wheels_front  # Specify dependency on the Flutter app service
    restart: always
