version: '3'

services:
  wheels_front:
    image: ccortesra/wheels_front:latest
    expose:
      - 8081
    restart: always
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Adjust the ports as needed
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the Nginx configuration file
      - ./nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
    depends_on:
      - wheels_front  # Specify dependency on the Flutter app service
    restart: always
    networks:
      - mynetwork

  wheelsunAuth:
    image: jnerdq/image-wheelsun_auth_ms
    expose:
      - 8080
    networks:
      - mynetwork

  wheelsun_user_ms:
    image: jivegabe/image-wheelsun_user_ms
    expose:
      - 8000
    networks:
      - mynetwork

  wheelsun_mq:
    image: rabbitmq:3.13-management
    expose:
      - 5672
      - 15672
    networks:
      - mynetwork
      
  wheelsun_transaction_ms:
    image: cquilaguy12/image-wheelsun_transaction_ms
    expose:
      - 3000

    networks:
      - mynetwork
      
  wheelsun_trip_ms:
    image: ccortesra/wheels
    expose:
      - 3002
    
    networks:
      - mynetwork

  wheelsun_ag:
    image: jivegabe/image-wheelsun_ag
    expose:
      - 8100
    networks:
      - mynetwork
    depends_on:
      - wheelsunAuth
      - wheelsun_user_ms
      - wheelsun_transaction_ms
      - wheelsun_trip_ms
      - wheelsun_mq

  ag_proxy:
    image: cquilaguy12/image-wheelsun_proxyag
    ports:
      - "81:81"
    networks:
      - mynetwork
    depends_on:
      - wheelsun_ag
    
networks:
  mynetwork:
    driver: bridge