version: '3'

services:
  wheels_front:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Adjust the ports as needed
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the Nginx configuration file
      - ./nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key

    depends_on:
      - wheels_front  # Specify dependency on the Flutter app service
    restart: always
