version: '3'

services:
  wheelsfront:
    image: ccortesra/wheels_front:latest
    expose:
      - 8081
    restart: always
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Adjust the ports as needed
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the Nginx configuration file
      - ./nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
    depends_on:
      - wheelsfront  # Specify dependency on the Flutter app service
    restart: always
    networks:
      - mynetwork

  wheelsunauth:
    image: jnerdq/image-wheelsun_auth_ms
    expose:
      - 8080
    networks:
      - mynetwork

  wheelsunuserms:
    image: jivegabe/image-wheelsun_user_ms
    expose:
      - 8000
    networks:
      - mynetwork

  wheelsunmq:
    image: rabbitmq:3.13-management
    expose:
      - 5672
      - 15672
    networks:
      - mynetwork
      
  wheelsuntransactionms:
    image: cquilaguy12/image-wheelsun_transaction_ms
    expose:
      - 3000

    networks:
      - mynetwork
      
  wheelsuntripms:
    image: ccortesra/wheels
    expose:
      - 3002
    
    networks:
      - mynetwork

  wheelsunag:
    image: jivegabe/image-wheelsun_ag-no_ldap
    expose:
      - 8100
    networks:
      - mynetwork
    depends_on:
      - wheelsunauth
      - wheelsunuserms
      - wheelsuntransactionms
      - wheelsuntripms
      - wheelsunmq

  nginx_wheelsunag:
    image: cquilaguy12/image-wheelsun_proxyag
    ports:
      - 81
      - 444
    networks:
      - mynetwork
    depends_on:
      - wheelsunag
    
networks:
  mynetwork:
    driver: bridge